parser: babel-eslint
env:
  browser: true
  es6: true
  jasmine: true
extends: eslint:recommended
plugins:
  - jasmine
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2019
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  lines-between-class-members: [error, always, { exceptAfterSingleLine: true }]
